### ISSUE TITLE
Should probably add a README

### ISSUE THREAD

**Issue by rosenpin** [goatslacker/pokemon-go-iv-calculator#1]
You would probably want to add a README explaining how to compile the program and how to use it.
What it does etc...

**Comment by goatslacker** [comment]
I was planning on it after I had a React frontend for it since it's just CLI atm.

FWIW, if you'd like to use it:
1. Clone the repo.
2. npm install chalk
3. run `node index.js growlithe 700 77 3500`

where:
  growlithe = name of pokemon
  700 = cp
  77 = hp
  3500  = stardust

if you know your Pokemon's level you can append it to the end of that list.

eg:

`node index.js growlithe 700 77 3500 22`

**Comment by runoncedev** [comment]
Readme file was recently added in commit https://github.com/goatslacker/pokemon-go-iv-calculator/commit/2546e90a30011a74ca649eb17fc805e2e6c6a075#diff-04c6e90faac2675aa89e2176d2eec7d8.

Someone should close this issue.
